from __future__ import annotations

import json
import random
import sys
from pathlib import Path

STUDY_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(STUDY_ROOT))

from harness import metrics

OUT = Path(__file__).resolve().parent / "data" / "citation_sweep_fixture.json"

FIXTURE_LABEL = (
    "SYNTHETIC FIXTURE — not experimental data. Generated by "
    "figures/make_sweep_fixture.py to exercise the renderer before the "
    "condition grid runs."
)

PRINCIPLES = ["p01", "p02", "p03", "p04"]


def synthetic_decisions(n: int = 480, seed: int = 8) -> list[dict]:
    rng = random.Random(seed)
    rows = []
    for _ in range(n):
        gold = rng.sample(PRINCIPLES, rng.choice([1, 1, 2]))
        roll = rng.random()
        if roll < 0.42:
            cell, span_f1 = "TP", min(1.0, rng.betavariate(6, 2))
        elif roll < 0.62:
            cell, span_f1 = "TP", rng.betavariate(2, 3)
        elif roll < 0.80:
            cell, span_f1 = "TN", None
        elif roll < 0.91:
            cell, span_f1 = "FN", None
        else:
            cell, span_f1 = "FP", None

        if cell == "TP" and span_f1 is not None and span_f1 > 0.6:
            cited = gold if rng.random() < 0.62 else rng.sample(PRINCIPLES, 1)
        else:
            cited = gold if rng.random() < 0.34 else rng.sample(PRINCIPLES, 1)

        rows.append(
            {
                "answer_score": {"cell": cell, "span_f1": span_f1},
                "citation_eval": metrics.citation_eval(cited, gold).to_dict(),
            }
        )
    return rows


def main() -> int:
    rows = synthetic_decisions()
    sweep = metrics.citation_correctness_sweep(
        rows, citation_f1_thresholds=[0.25, 0.5, 0.75, 1.0]
    )
    sweep["__fixture__"] = True
    sweep["__label__"] = FIXTURE_LABEL
    sweep["source"] = {
        "kind": "synthetic",
        "generator": "figures/make_sweep_fixture.py",
        "n_decisions": len(rows),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(sweep, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} synthetic decisions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
